# Generated by Django 5.2.4 on 2025-09-27 11:45

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('Katerini', 'Katerini'), ('Thessaloniki', 'Thessaloniki'), ('Kavala', 'Kavala'), ('Serres', 'Serres'), ('Drama', 'Drama'), ('Kastoria', 'Kastoria'), ('Florina', 'Florina'), ('Edessa', 'Edessa'), ('Naousa', 'Naousa'), ('Kozani', 'Kozani'), ('Grevena', 'Grevena'), ('Komotini', 'Komotini'), ('Xanthi', 'Xanthi'), ('Alexandroupoli', 'Alexandroupoli'), ('Orestiada', 'Orestiada'), ('Larisa', 'Larisa'), ('Volos', 'Volos'), ('Trikala', 'Trikala'), ('Karditsa', 'Karditsa'), ('Ioannina', 'Ioannina'), ('Arta', 'Arta'), ('Preveza', 'Preveza'), ('Igoumenitsa', 'Igoumenitsa'), ('Athina', 'Athina'), ('Lamia', 'Lamia'), ('Chalkida', 'Chalkida'), ('Thiva', 'Thiva'), ('Patra', 'Patra'), ('Kalamata', 'Kalamata'), ('Tripoli', 'Tripoli'), ('Sparti', 'Sparti'), ('Nafplio', 'Nafplio'), ('Corinth', 'Corinth'), ('Megara', 'Megara'), ('Irakleio', 'Irakleio'), ('Chania', 'Chania'), ('Rethymno', 'Rethymno'), ('Agios Nikolaos', 'Agios Nikolaos'), ('Sitia', 'Sitia')], max_length=60)),
                ('contact_email', models.EmailField(max_length=254)),
                ('organization_type', models.CharField(choices=[('Municipality', 'Municipality'), ('Private Company', 'Private Company')], max_length=50)),
                ('established_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('bin_type', models.CharField(choices=[('Organic-Bio', 'Organic-Bio'), ('Plastic', 'Plastic'), ('General', 'General'), ('Glass', 'Glass'), ('Batteries', 'Batteries'), ('Metal', 'Metal'), ('Recycling', 'Recycling')], max_length=20)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Capacity (Kg)')),
                ('current_fill_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current fill level (Kg)')),
                ('critical_threshold', models.DecimalField(decimal_places=2, default=80, max_digits=10, verbose_name='Critical threshold (%)')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Under maintenance', 'Under maintenance')], default='Available', max_length=20)),
                ('last_collected_at', models.DateTimeField(default=datetime.datetime(2025, 9, 27, 11, 45, 48, 868826, tzinfo=datetime.timezone.utc))),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='smart_waste_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Driver', 'Driver')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organizations', models.ManyToManyField(related_name='users', to='smart_waste_app.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PickUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_weight', models.IntegerField(default=100)),
                ('auto_assign_truck', models.BooleanField(default=True, help_text='Automatically truck selection for optimal pickup.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Pending', max_length=12)),
                ('urgency_level', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical'), ('Hazardous', 'Hazardous')], default='Normal', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('now', models.BooleanField(default=False, help_text='The pick-up will be carried out now.')),
                ('distance', models.DecimalField(decimal_places=1, default=-1, max_digits=5)),
                ('expected_time', models.DecimalField(decimal_places=1, default=-1, max_digits=5)),
                ('route', models.CharField(default='NULL -> NULL', max_length=200)),
                ('truck_speed', models.IntegerField(default=0)),
                ('auto_assign_all', models.BooleanField(default=False, help_text='Automatically assign all available trucks to all bins.')),
                ('warnings', models.CharField(blank=True, max_length=200, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='smart_waste_app.bin')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='smart_waste_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Partial', 'Partial'), ('Failed', 'Failed')], default='Partial', max_length=10)),
                ('pickup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='smart_waste_app.pickuprequest')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=8, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1000)], verbose_name='Capacity (Kg)')),
                ('current_load', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Almost full', 'Almost full'), ('Full', 'Full')], default='Available', max_length=20)),
                ('speed_category', models.CharField(choices=[('Slow', 'Slow'), ('Normal', 'Normal'), ('Fast', 'Fast')], default='Normal', max_length=10)),
                ('speed', models.IntegerField()),
                ('unload', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='smart_waste_app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='smart_waste_app.truck'),
        ),
    ]
