# Generated by Django 5.2.4 on 2025-11-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='threshold_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
